/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculadora */

#ifndef _Included_Calculadora
#define _Included_Calculadora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculadora
 * Method:    sumar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_sumar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    restar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_restar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    multiplicar
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_multiplicar
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculadora
 * Method:    dividir
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculadora_dividir
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
